create extension if not exists pgcrypto;

create table if not exists public.profiles (
user_id bigint generated by default as identity primary key,
auth_user_id uuid not null unique references auth.users(id) on delete cascade,
full_name text not null,
email text not null unique,
phone_number text,
role text not null default 'donor',
status text not null default 'active',
created_at timestamptz not null default now()
);

create table if not exists public.campaigns (
campaign_id bigint generated by default as identity primary key,
title text not null,
description text not null,
goal_amount numeric(12,2) not null default 0,
raised_amount numeric(12,2) not null default 0,
category text not null default 'community',
status text not null default 'pending',
organizer_id bigint not null references public.profiles(user_id) on delete cascade,
organizer_name text,
image_url text,
created_at timestamptz not null default now()
);

create table if not exists public.campaign_updates (
update_id bigint generated by default as identity primary key,
campaign_id bigint not null references public.campaigns(campaign_id) on delete cascade,
content text not null,
posted_at timestamptz not null default now()
);

create table if not exists public.donations (
donation_id bigint generated by default as identity primary key,
campaign_id bigint not null references public.campaigns(campaign_id) on delete cascade,
donor_id bigint not null references public.profiles(user_id) on delete cascade,
amount numeric(12,2) not null,
payment_status text not null default 'pending',
payment_provider text not null default 'chapa',
payment_reference text unique,
checkout_url text,
paid_at timestamptz,
is_anonymous boolean not null default false,
campaign_title text,
created_at timestamptz not null default now()
);

create table if not exists public.comments (
comment_id bigint generated by default as identity primary key,
campaign_id bigint not null references public.campaigns(campaign_id) on delete cascade,
user_id bigint not null references public.profiles(user_id) on delete cascade,
content text not null,
full_name text,
created_at timestamptz not null default now()
);

create table if not exists public.withdrawals (
withdrawal_id bigint generated by default as identity primary key,
campaign_id bigint not null references public.campaigns(campaign_id) on delete cascade,
organizer_id bigint not null references public.profiles(user_id) on delete cascade,
amount numeric(12,2) not null,
status text not null default 'pending',
bank_account text,
campaign_title text,
request_date timestamptz not null default now()
);

create table if not exists public.reports (
report_id bigint generated by default as identity primary key,
object_type text not null,
object_id bigint,
reason text not null,
reporter_id bigint references public.profiles(user_id) on delete set null,
created_at timestamptz not null default now()
);

create index if not exists campaigns_status_idx on public.campaigns(status);
create index if not exists campaigns_organizer_idx on public.campaigns(organizer_id);
create index if not exists donations_campaign_idx on public.donations(campaign_id);
create index if not exists donations_status_idx on public.donations(payment_status);
create index if not exists donations_reference_idx on public.donations(payment_reference);
create index if not exists comments_campaign_idx on public.comments(campaign_id);
create index if not exists withdrawals_campaign_idx on public.withdrawals(campaign_id);

alter table public.profiles enable row level security;
alter table public.campaigns enable row level security;
alter table public.campaign_updates enable row level security;
alter table public.donations enable row level security;
alter table public.comments enable row level security;
alter table public.withdrawals enable row level security;
alter table public.reports enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
using (
auth.uid() = auth_user_id
or exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
using (
auth.uid() = auth_user_id
or exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
)
with check (
auth.uid() = auth_user_id
or exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
);

drop policy if exists "campaigns_select_public" on public.campaigns;
create policy "campaigns_select_public"
on public.campaigns
for select
using (
status = 'approved'
or exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
or organizer_id in (
select user_id from public.profiles
where auth_user_id = auth.uid()
)
);

drop policy if exists "campaigns_insert_organizer" on public.campaigns;
create policy "campaigns_insert_organizer"
on public.campaigns
for insert
with check (
exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role in ('organizer', 'admin')
)
);

drop policy if exists "campaigns_update_owner_or_admin" on public.campaigns;
create policy "campaigns_update_owner_or_admin"
on public.campaigns
for update
using (
exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
or organizer_id in (
select user_id from public.profiles
where auth_user_id = auth.uid()
)
)
with check (
exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
or organizer_id in (
select user_id from public.profiles
where auth_user_id = auth.uid()
)
);

drop policy if exists "campaign_updates_select" on public.campaign_updates;
create policy "campaign_updates_select"
on public.campaign_updates
for select
using (
exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
or campaign_id in (
select c.campaign_id
from public.campaigns c
join public.profiles p on p.user_id = c.organizer_id
where p.auth_user_id = auth.uid()
or c.status = 'approved'
)
);

drop policy if exists "campaign_updates_insert_owner_or_admin" on public.campaign_updates;
create policy "campaign_updates_insert_owner_or_admin"
on public.campaign_updates
for insert
with check (
exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
or campaign_id in (
select c.campaign_id
from public.campaigns c
join public.profiles p on p.user_id = c.organizer_id
where p.auth_user_id = auth.uid()
)
);

drop policy if exists "donations_select_own_or_admin" on public.donations;
create policy "donations_select_own_or_admin"
on public.donations
for select
using (
exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
or donor_id in (
select user_id from public.profiles
where auth_user_id = auth.uid()
)
or campaign_id in (
select c.campaign_id
from public.campaigns c
join public.profiles p on p.user_id = c.organizer_id
where p.auth_user_id = auth.uid()
)
);

drop policy if exists "donations_insert_signed_in" on public.donations;
create policy "donations_insert_signed_in"
on public.donations
for insert
with check (
donor_id in (
select user_id from public.profiles
where auth_user_id = auth.uid()
)
or exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
);

alter table public.donations
add column if not exists payment_provider text not null default 'chapa',
add column if not exists payment_reference text,
add column if not exists checkout_url text,
add column if not exists paid_at timestamptz;

create unique index if not exists donations_payment_reference_unique_idx on public.donations(payment_reference)
where payment_reference is not null;

create index if not exists donations_payment_status_idx on public.donations(payment_status);

drop policy if exists "comments_select_public" on public.comments;
create policy "comments_select_public"
on public.comments
for select
using (true);

drop policy if exists "comments_insert_signed_in" on public.comments;
create policy "comments_insert_signed_in"
on public.comments
for insert
with check (
user_id in (
select user_id from public.profiles
where auth_user_id = auth.uid()
)
or exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
);

drop policy if exists "withdrawals_select_owner_or_admin" on public.withdrawals;
create policy "withdrawals_select_owner_or_admin"
on public.withdrawals
for select
using (
exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
or organizer_id in (
select user_id from public.profiles
where auth_user_id = auth.uid()
)
);

drop policy if exists "withdrawals_insert_owner" on public.withdrawals;
create policy "withdrawals_insert_owner"
on public.withdrawals
for insert
with check (
organizer_id in (
select user_id from public.profiles
where auth_user_id = auth.uid()
)
or exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
);

drop policy if exists "reports_admin_only" on public.reports;
create policy "reports_admin_only"
on public.reports
for all
using (
exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
)
with check (
exists (
select 1 from public.profiles p
where p.auth_user_id = auth.uid()
and p.role = 'admin'
)
);

create or replace function public.handle_new_profile()
returns trigger
language plpgsql
security definer
as $$
begin
insert into public.profiles (
auth_user_id,
full_name,
email,
phone_number,
role,
status
)
values (
new.id,
coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
new.email,
new.raw_user_meta_data->>'phone_number',
coalesce(new.raw_user_meta_data->>'role', 'donor'),
'active'
)
on conflict (auth_user_id)
do update set
email = excluded.email,
full_name = excluded.full_name,
phone_number = excluded.phone_number,
role = excluded.role;

return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_profile();

create or replace function public.handle_donation_insert()
returns trigger
language plpgsql
security definer
as $$
begin
if (tg_op = 'INSERT' and new.payment_status = 'completed') or (tg_op = 'UPDATE' and old.payment_status is distinct from 'completed' and new.payment_status = 'completed') then
update public.campaigns
set raised_amount = coalesce(raised_amount, 0) + coalesce(new.amount, 0)
where campaign_id = new.campaign_id;
end if;

return new;
end;
$$;

drop trigger if exists on_donation_created on public.donations;

create trigger on_donation_created
after insert or update of payment_status on public.donations
for each row
execute function public.handle_donation_insert();
